Repository grafana/alloy, pull requests merged in 2024-04, with the labels that each got.

#144 Update install link in README.md
  README.md
Labels: type/docs

#164 Update the Ansible doc to use the alloy role instead of Agent
  docs/sources/get-started/install/ansible.md
Labels: type/docs, backport release/v1.0

#168 Add a shared content admonition for the Agent deprecation
  docs/sources/shared/agent-deprecation.md
Labels: type/docs, backport release/v1.0

#180 Add tip to clarify Alloy comes from Agent
  docs/sources/_index.md
  docs/sources/_index.md.t
Labels: type/docs, backport release/v1.0

#181 Fixed Luhn Typo
  docs/sources/reference/components/loki.process.md
Labels: type/docs, backport release/v1.0

#186 Fix path typo in Alloy Linux config topic
  docs/sources/tasks/configure/configure-linux.md
Labels: type/docs, backport release/v1.0

#558 docs: fix "graalloy" typo
  docs/sources/tasks/migrate/from-static.md
Labels: backport release/v1.0

#579 Fix broken link to install topic
  docs/sources/tasks/migrate/from-flow.md
Labels: type/docs, backport release/v1.0

#568 Update cards on main Alloy docs landing page
  docs/sources/_index.md
  docs/sources/_index.md.t
Labels: type/docs, backport release/v1.0

#577 Add alias to fix link in migration topic
  docs/sources/get-started/install/_index.md
Labels: type/docs, backport release/v1.0

#588 Remove double slash from relative URL
  docs/sources/reference/config-blocks/argument.md
Labels: backport release/v1.0

#594 Update loki.source.api.md
  docs/sources/reference/components/loki.source.api.md
Labels: type/docs, backport release/v1.0

#593 Fix bad links and canonical URLs
  docs/sources/concepts/custom_components.md
  docs/sources/reference/cli/run.md
  docs/sources/reference/cli/tools.md
  docs/sources/reference/components/otelcol.auth.bearer.md
  docs/sources/reference/components/otelcol.exporter.loadbalancing.md
  docs/sources/tasks/migrate/from-flow.md
  docs/sources/tasks/monitor/component_metrics.md
  docs/sources/tasks/monitor/controller_metrics.md
Labels: type/docs, backport release/v1.0

#166 packaging: properly unregister Alloy when uninstalling on Windows
  CHANGELOG.md
  packaging/windows/install_script.nsis
Labels: backport-to-agent

#606 Fix Prometheus example in Beyla's docs
  docs/sources/reference/components/beyla.ebpf.md
Labels: backport release/v1.0

#611 Update opentelemetry-to-lgtm-stack.md
  docs/sources/tasks/opentelemetry-to-lgtm-stack.md
Labels: backport release/v1.0

#612 docs: Corrects `path` to `exe_path` in Beyla's docs
  docs/sources/reference/components/beyla.ebpf.md
Labels: backport release/v1.0

#158 Refactor mimir.rules.kubernetes component (port from agent repo)
  internal/component/mimir/rules/kubernetes/debug.go
  internal/component/mimir/rules/kubernetes/events.go
  internal/component/mimir/rules/kubernetes/events_test.go
  internal/component/mimir/rules/kubernetes/rules.go
Labels: backport-to-agent

#640 ci: enable CD for commits to main
  .drone/drone.yml
  .drone/pipelines/publish.jsonnet
  tools/ci/docker-containers
  tools/ci/docker-containers-windows
  tools/image-tag
  tools/image-tag-docker
Labels: backport-to-agent:no

#650 ci: fix issue where creating tag files made working branch dirty
  .gitignore
Labels: backport-to-agent:no

#648 mimir.rules.kubernetes: Add warning about clustering to docs
  docs/sources/reference/components/mimir.rules.kubernetes.md
Labels: type/docs, backport release/v1.0, backport-to-agent

#601 loki.source.kubernetes: restart tailers less aggressively
  CHANGELOG.md
  internal/component/loki/source/kubernetes/kubetail/tailer.go
Labels: backport-to-agent:no

#605 Add alert support for dedicated deployments for allow, alloy-logs, alloy-events, etc
  operations/alloy-mixin/alerts/clustering.libsonnet
Labels: backport-to-agent

#635 misc: switch to using a GitHub app for Helm chart releases
  .drone/pipelines/build_images.jsonnet
  .github/workflows/helm-release.yml
Labels: backport-to-agent:no

#665 tools/ci: fix pushed Windows "latest" name
  CHANGELOG.md
  Makefile
  docs/sources/get-started/install/docker.md
  tools/ci/docker-containers-windows
Labels: backport release/v1.0

#667 [release/v1.0] tools/ci: fix pushed Windows "latest" name (#665)
  CHANGELOG.md
  Makefile
  docs/sources/get-started/install/docker.md
  tools/ci/docker-containers-windows
Labels: backport

#672 Removed extra tab in yaml example
  docs/sources/tasks/configure/configure-kubernetes.md
Labels: backport release/v1.0

#615 fix(pyroscope/scrape): add support for scraping `alloy`'s internal domain
  CHANGELOG.md
  internal/component/pyroscope/scrape/manager.go
  internal/component/pyroscope/scrape/manager_test.go
  internal/component/pyroscope/scrape/scrape.go
  internal/component/pyroscope/scrape/scrape_loop.go
  internal/component/pyroscope/scrape/scrape_loop_test.go
  internal/component/pyroscope/scrape/scrape_test.go
Labels: backport-to-agent

#661 pyroscope.java: Add glibc detection for arm64
  internal/component/pyroscope/java/asprof/asprof.go
Labels: bug, backport-to-agent

#676 Fix compatibility list
  docs/sources/introduction/_index.md
Labels: backport release/v1.0

#662 pyroscope.scrape: Standardize profile names
  internal/component/pyroscope/scrape/target.go
  internal/component/pyroscope/scrape/target_test.go
Labels: enhancement

#674 docs: remove 'd' from duration values spec
  docs/sources/concepts/configuration-syntax/expressions/types_and_values.md
Labels: backport release/v1.0, backport-to-agent

#655 Add details for setting memory limit automatically.
  CHANGELOG.md
  docs/sources/reference/cli/run.md
  go.mod
  go.sum
  internal/alloycli/cmd_run.go
  internal/featuregate/featuregate.go
  internal/featuregate/featuregate_test.go
Labels: backport-to-agent:no

#632 fix(faro/receiver): extra_log_labels with empty value now map to existing value in log line
  CHANGELOG.md
  internal/component/faro/receiver/exporters.go
  internal/component/faro/receiver/receiver_test.go
Labels: backport-to-agent

#683 docs(operator): typo in MetricsInstance
  docs/sources/tasks/migrate/from-operator.md
Labels: type/docs, backport release/v1.0

#646 Fix nested import git data path
  CHANGELOG.md
  internal/alloy/import_test.go
  internal/alloy/internal/controller/node_config_import.go
  internal/alloy/testdata/.gitignore
  internal/alloy/testdata/import_git/import_git_3.txtar
  internal/alloy/testdata/repo.git.tar
  internal/alloy/testdata/repo2.git.tar
Labels: backport-to-agent

#706 Remove stale note in loki.source.podlogs
  docs/sources/reference/components/loki.source.podlogs.md
Labels: type/docs, backport release/v1.0

#678 Update pyroscope/ebpf to v0.4.6
  docs/sources/reference/components/pyroscope.ebpf.md
  go.mod
  go.sum
  internal/build/build.go
  internal/component/pyroscope/ebpf/args.go
  internal/component/pyroscope/ebpf/ebpf_linux.go
  internal/component/pyroscope/ebpf/ebpf_linux_test.go
Labels: backport-to-agent

#709 Revert reference of Alloy to Agent
  docs/sources/reference/components/loki.source.podlogs.md
Labels: type/docs, backport release/v1.0, backport-to-agent

#721 prometheus.remote_write: notify remote_write of data upon WAL commit
  CHANGELOG.md
  internal/component/prometheus/remotewrite/remote_write.go
  internal/static/metrics/wal/wal.go
  internal/static/metrics/wal/wal_test.go
Labels: backport-to-agent

#724 packaging: don't assume /var/lib/alloy exists when running chown
  CHANGELOG.md
  packaging/deb/control/postinst
  packaging/rpm/control/postinst
Labels: backport-to-agent
