Repository grafana/alloy, pull requests merged in 2025-09, with the labels that each got.

#4315 fix: move to linux test folder
  internal/converter/internal/staticconvert/testdata_linux/promtail_metrics.alloy
  internal/converter/internal/staticconvert/testdata_linux/promtail_metrics.diags
  internal/converter/internal/staticconvert/testdata_linux/promtail_metrics.yaml
Labels: os:windows

#4317 fix: close open files so test clean up succeeds on windows
  internal/component/common/loki/positions/positions_test.go
  internal/static/metrics/wal/wal_test.go
Labels: os:windows

#4305 remote_write: Only use a slice when we have a hash conflict
  CHANGELOG.md
  internal/static/metrics/wal/series.go
  internal/static/metrics/wal/series_test.go
  internal/static/metrics/wal/wal.go
  internal/static/metrics/wal/wal_test.go
Labels: c/prometheus.remote_write

#4341 Update prometheus.write.queue.md
  docs/sources/reference/components/prometheus/prometheus.write.queue.md
Labels: type/docs

#4242 pyroscope.write: add latency metrics
  CHANGELOG.md
  docs/sources/reference/components/pyroscope/pyroscope.write.md
  internal/component/pyroscope/write/metrics.go
  internal/component/pyroscope/write/write.go
Labels: type/docs

#4445 Bump walqueue to eliminate duplicate calls to size
  CHANGELOG.md
  go.mod
  go.sum
Labels: c/prometheus.write.queue

#4502 Fix Windows installer version
  .github/workflows/publish-alloy-release.yml
Labels: os:windows

#4451 Implement structured_metadata_drop stage for loki.process
  CHANGELOG.md
  docs/sources/reference/components/loki/loki.process.md
  internal/component/loki/process/stages/pipeline.go
  internal/component/loki/process/stages/stage.go
  internal/component/loki/process/stages/structured_metadata_drop.go
  internal/component/loki/process/stages/structured_metadata_drop_test.go
Labels: type/docs
